#ifndef __PIO_NAND_H
#define __PIO_NAND_H

#include "hardware/pio.h"
#include "nand.pio.h" // generated by PIO toolchain
#include "pico/stdlib.h"

typedef struct nand_pio_inst {
    PIO pio;
    nand_pins_t pins;
} nand_pio_inst_t;

typedef struct chip_id_info {
    uint8_t maker_code; //              0x98 for TC58NVG2S0HBAI6
    uint8_t device_code; //             0xDC for TC58NVG2S0HBAI6
    uint8_t chip_num_and_cell_type; //  0x90 for TC58NVG2S0HBAI6
    uint8_t pg_blk_sz_and_io_width; //  0x26 for TC58NVG2S0HBAI6
    uint8_t district_number; //         0x76 for TC58NVG2S0HBAI6 (bits )
} chip_id_info_t;

void nand_pio_read_id(nand_pio_inst_t* nand, chip_id_info_t* id);
void nand_pio_read_page(nand_pio_inst_t* nand, uint32_t pageno);
// TODO: Fancier reading
// void nand_pio_read_col_and_page(nand_pio_inst_t* nand, uint32_t pageno, uint16_t colno);

#endif
